// Fichier partagé - liste de toutes les colonnes du CRM
// Importé par MondayTable.jsx et TeamList.jsx

export const ALL_COLUMNS = [
  { label: 'ID',            key: 'lead_id' },
  { label: 'Funbooster',    key: 'funebooster' },
  { label: 'Entreprise',    key: 'nom_entreprise' },
  { label: 'Forme Juridique', key: 'forme_juridique' },
  { label: 'Gérant',        key: 'gerant' },
  { label: 'Nº Siret',      key: 'siret' },
  { label: 'Tranche Effectif', key: 'tranche_effectif' },
  { label: 'Secteur Act.',  key: 'secteur_activite' },
  { label: 'Libellé Act.',  key: 'libelle_activite' },
  { label: 'Opco',          key: 'nom_opco' },
  { label: 'IDCC',          key: 'idcc' },
  { label: 'IDCC 2',        key: 'idcc_2' },
  { label: 'Code NAF',      key: 'code_naf' },
  { label: 'Pappers',       key: 'pappers' },
  { label: 'Téléphone',     key: 'tel' },
  { label: 'Mobile',        key: 'mobile' },
  { label: 'Adresse',       key: 'adresse' },
  { label: 'Code Postal',   key: 'code_postal' },
  { label: 'Code Dépt.',    key: 'code_departement' },
  { label: 'Statut',        key: 'status' },
  { label: 'Statut Projet',    key: 'status_rdv' },
  { label: 'E-mail',        key: 'email' },
  { label: 'Site Web',      key: 'site_web' },
  { label: 'Statut Gérant', key: 'statut_gerant' },
  { label: 'Nb Salariés',   key: 'nb_salaries' },
  { label: 'Nb Apprentis',  key: 'nb_apprentis' },
  { label: 'Date Modif',    key: 'date_modification' },
  { label: 'Client OF',     key: 'client_of' },
  { label: 'Opcosign',      key: 'opcosign' },
  { label: 'Budget Opco',   key: 'budget_opco' },
  { label: 'Année Budget',  key: 'annee_budget' },
  { label: 'Date RDV',      key: 'date_rdv' },
  { label: 'Heure RDV',     key: 'heure_rdv' },
  { label: 'Type RDV',      key: 'type_rdv' },
  { label: 'RDV Honoré ?',  key: 'rdv_honore' },
  { label: 'Proposition',   key: 'proposition' },
  { label: 'Signé',         key: 'signe' },
  { label: 'Date Sign',     key: 'date_signe' },
  { label: 'CA Signé HT',   key: 'ca_signe_ht' },
  { label: 'Nb Heures',     key: 'nb_heures_formation' },
  { label: 'TX Horaire',    key: 'tx_horaire_ca' },
  { label: 'Campagne',      key: 'campagne_act' },
  { label: 'PEC',           key: 'pec' },
  { label: 'Échéances PEC', key: 'echeances_pec' },
  { label: 'Suivi Form.',   key: 'suivi_formation' },
  { label: 'Commentaires',  key: 'observation' },
];
